itemsData = {
    -- Clothe items
    c_necklace                    = { name = "c_necklace", label = "Necklace (Clothe)", clothe = true, weight = 0, type = "item", unique = true, useable = false, shouldClose = false, description = "" },
    c_bproof                      = { name = "c_bproof", label = "Bullet Proof (Clothe)", clothe = true, weight = 0, type = "item", unique = true, useable = false, shouldClose = false, description = "" },
    c_decal                       = { name = "c_decal", label = "Decals (Clothe)", clothe = true, weight = 0, type = "item", unique = true, useable = false, shouldClose = false, description = "" },
    c_torso                       = { name = "c_torso", label = "Torso (Clothe)", clothe = true, weight = 0, type = "item", unique = true, useable = false, shouldClose = false, description = "" },
    c_mask                        = { name = "c_mask", label = "Mask (Clothe)", clothe = true, weight = 0, type = "item", unique = true, useable = false, shouldClose = false, description = "" },
    c_helmet                      = { name = "c_helmet", label = "Hat (Clothe)", clothe = true, weight = 0, type = "item", unique = true, useable = false, shouldClose = false, description = "" },
    c_glasses                     = { name = "c_glasses", label = "Glasses (Clothe)", clothe = true, weight = 0, type = "item", unique = true, useable = false, shouldClose = false, description = "" },
    c_bag                         = { name = "c_bag", label = "Bag (Clothe)", clothe = true, weight = 0, type = "item", unique = true, useable = false, shouldClose = false, description = "" },
    c_pants                       = { name = "c_pants", label = "Pants (Clothe)", clothe = true, weight = 0, type = "item", unique = true, useable = false, shouldClose = false, description = "" },
    c_shoes                       = { name = "c_shoes", label = "Shoes (Clothe)", clothe = true, weight = 0, type = "item", unique = true, useable = false, shouldClose = false, description = "" },
    c_bracelet                    = { name = "c_bracelet", label = "Bracelet (Clothe)", clothe = true, weight = 0, type = "item", unique = true, useable = false, shouldClose = false, description = "" },
    c_watch                       = { name = "c_watch", label = "Watch (Clothe)", clothe = true, weight = 0, type = "item", unique = true, useable = false, shouldClose = false, description = "" },
    c_ear                         = { name = "c_ear", label = "Ear (Clothe)", clothe = true, weight = 0, type = "item", unique = true, useable = false, shouldClose = false, description = "" },
    kposet                        = { name = "kposet", label = "Clothes Bag", weight = 100, type = "item", unique = true, useable = true, shouldClose = false, description = "Special Bag to Store Your Clothes" },          -- Clothe small bag item
    bkposet                       = { name = "bkposet", label = "Clothes Bag Plus", weight = 300, type = "item", unique = true, useable = true, shouldClose = false, description = "Special Bag to Store Your Clothes" },    -- Clothe big bag item
    clothe_set                    = { name = 'clothe_set', label = 'Clothe Set', weight = 0, type = 'item', image = 'clothe_set.png', clothe = true, unique = true, useable = true, shouldClose = false, description = '' }, -- Clothe set item

    -- Police ammo items
    police_stungun_ammo           = { rareName = "weaponPoliceAmmo", name = 'police_stungun_ammo', label = 'Pollice Stungun ammo', weight = 200, type = 'item', image = 'stungun_ammo.webp', unique = false, useable = true, shouldClose = true, description = 'Ammo for Stungun' },
    police_pistol_ammo            = { rareName = "weaponPoliceAmmo", name = 'police_pistol_ammo', label = 'Pollice Pistol ammo', weight = 200, type = 'item', image = 'pistol_ammo.webp', unique = false, useable = true, shouldClose = true, description = 'Ammo for Pistols' },
    police_rifle_ammo             = { rareName = "weaponPoliceAmmo", name = 'police_rifle_ammo', label = 'Pollice Rifle ammo', weight = 1000, type = 'item', image = 'rifle_ammo.webp', unique = false, useable = true, shouldClose = true, description = 'Ammo for Rifles' },
    police_smg_ammo               = { rareName = "weaponPoliceAmmo", name = 'police_smg_ammo', label = 'Pollice SMG ammo', weight = 500, type = 'item', image = 'smg_ammo.webp', unique = false, useable = true, shouldClose = true, description = 'Ammo for Sub Machine Guns' },
    police_shotgun_ammo           = { rareName = "weaponPoliceAmmo", name = 'police_shotgun_ammo', label = 'Pollice Shotgun ammo', weight = 500, type = 'item', image = 'shotgun_ammo.webp', unique = false, useable = true, shouldClose = true, description = 'Ammo for Shotguns' },
    police_mg_ammo                = { rareName = "weaponPoliceAmmo", name = 'police_mg_ammo', label = 'Pollice MG ammo', weight = 1000, type = 'item', image = 'mg_ammo.webp', unique = false, useable = true, shouldClose = true, description = 'Ammo for Machine Guns' },
    police_snp_ammo               = { rareName = "weaponPoliceAmmo", name = 'police_snp_ammo', label = 'Pollice Sniper ammo', weight = 1000, type = 'item', image = 'rifle_ammo.webp', unique = false, useable = true, shouldClose = true, description = 'Ammo for Sniper Rifles' },
    police_emp_ammo               = { rareName = "weaponPoliceAmmo", name = 'police_emp_ammo', label = 'Pollice EMP Ammo', weight = 200, type = 'item', image = 'emp_ammo.webp', unique = false, useable = true, shouldClose = true, description = 'Ammo for EMP Launcher' },

    -- Ammo items
    pistol_ammo                   = { name = 'pistol_ammo', label = 'Pistol ammo', weight = 200, type = 'item', image = 'pistol_ammo.png', unique = false, useable = true, shouldClose = true, description = 'Ammo for Pistols' },
    rifle_ammo                    = { name = 'rifle_ammo', label = 'Rifle ammo', weight = 1000, type = 'item', image = 'rifle_ammo.png', unique = false, useable = true, shouldClose = true, description = 'Ammo for Rifles' },
    smg_ammo                      = { name = 'smg_ammo', label = 'SMG ammo', weight = 500, type = 'item', image = 'smg_ammo.png', unique = false, useable = true, shouldClose = true, description = 'Ammo for Sub Machine Guns' },
    shotgun_ammo                  = { name = 'shotgun_ammo', label = 'Shotgun ammo', weight = 500, type = 'item', image = 'shotgun_ammo.png', unique = false, useable = true, shouldClose = true, description = 'Ammo for Shotguns' },
    mg_ammo                       = { name = 'mg_ammo', label = 'MG ammo', weight = 1000, type = 'item', image = 'mg_ammo.png', unique = false, useable = true, shouldClose = true, description = 'Ammo for Machine Guns' },
    snp_ammo                      = { name = 'snp_ammo', label = 'Sniper ammo', weight = 1000, type = 'item', image = 'rifle_ammo.png', unique = false, useable = true, shouldClose = true, description = 'Ammo for Sniper Rifles' },
    emp_ammo                      = { name = 'emp_ammo', label = 'EMP Ammo', weight = 200, type = 'item', image = 'emp_ammo.png', unique = false, useable = true, shouldClose = true, description = 'Ammo for EMP Launcher' },

    -- Test Items
    testburger                    = {
        name = "testburger",
        label = 'Test Burger',
        weight = 220,
        useable = true,
        client = {
            image = 'burger_chicken.png',
            status = { hunger = 200000, thirst = 10000 },
            anim = { dict = 'missheistdockssetup1clipboard@idle_a', clip = 'idle_a', flag = 49 },
            prop = { model = `prop_rolled_sock_02`, pos = vec3(-0.14, -0.14, -0.08), rot = vec3(-50.0, -50.0, 0.0) },
            usetime = 2500,
            export = 'tgiann_inventory_examples.testburger' -- Script Name . Function name
        },
        server = {
            export = 'tgiann_inventory_examples.testburger', -- Script Name . Function name
        },
        unique = true
    },
    testbandage                   = {
        name = "testbandage",
        label = 'Bandage',
        weight = 115,
        useable = true,
        client = {
            anim = { dict = 'missheistdockssetup1clipboard@idle_a', clip = 'idle_a', flag = 49 },
            prop = { model = `prop_rolled_sock_02`, pos = vec3(-0.14, -0.14, -0.08), rot = vec3(-50.0, -50.0, 0.0) },
            disable = { move = true, car = true, combat = true },
            usetime = 2500,
        },
        buttons = {
            {
                label = 'Custom Button',
                action = function(slot)
                    print('Custom Button', slot)
                end
            }
        },
        add = function(amount)
            print('Added', amount)
        end,
        remove = function(amount)
            print('Removed', amount)
        end
    },
    --Money as Item
    money_item                    = { name = 'money_item', label = 'Money', weight = 0, type = 'item', image = 'money.webp', unique = false, useable = false, shouldClose = false, description = 'Green Paper' },

    television                    = { name = 'television', label = 'Television', weight = 100, type = 'item', image = 'television.png', unique = false, useable = true, shouldClose = true, description = '' },
    present                       = { name = 'present', label = 'Present', weight = 100, type = 'item', image = 'present.png', unique = false, useable = true, shouldClose = true, description = '' },
    phone                         = { name = 'phone', label = 'phone', weight = 100, type = 'item', image = 'phone.png', unique = true, useable = true, shouldClose = true, description = '' },

    testitem                      = { name = 'testitem', label = 'Test Item', weight = 0, type = 'item', image = 'testitem.png', unique = false, useable = true, shouldClose = true, description = 'testitem' },
    testitemuniq                  = { name = 'testitemuniq', label = 'Test Item Uniq', weight = 10, type = 'item', image = 'testitemuniq.png', unique = true, useable = true, shouldClose = true, description = 'testitemuniq' },
    testitemlong                  = { name = 'testitemlong', label = 'Test Item Long Long Long Name', weight = 0, type = 'item', image = 'testitemlong.png', unique = false, useable = true, shouldClose = true, description = 'testitemlong' },

    kurkakola                     = { name = 'kurkakola', label = 'Cola', weight = 100, type = 'item', image = 'kurkakola.png', unique = false, useable = true, shouldClose = true, description = '' },
    water_bottle                  = { name = 'water_bottle', label = 'Water bottle', weight = 100, type = 'item', image = 'water_bottle.png', unique = false, useable = true, shouldClose = true, description = '' },
    bread                         = { name = 'bread', label = 'Bread', weight = 100, type = 'item', image = 'bread.png', unique = false, useable = true, shouldClose = true, description = '' },
    water                         = { name = 'water', label = 'Water bottle', weight = 100, type = 'item', image = 'water.png', unique = false, useable = true, shouldClose = true, description = '' },
    radio                         = { name = 'radio', label = 'Radio', weight = 100, type = 'item', image = 'radio.png', unique = false, useable = true, shouldClose = true, description = '' },
    t_armor_heavy                 = { name = 't_armor_heavy', label = 'Heavy Armor', weight = 100, type = 'item', image = 't_armor_heavy.png', unique = true, useable = true, shouldClose = true, description = '' },
    t_armor_light                 = { name = 't_armor_light', label = 'Light Armor', weight = 100, type = 'item', image = 't_armor_light.png', unique = true, useable = true, shouldClose = true, description = '' },
    t_armor_plate_heavy           = { name = 't_armor_plate_heavy', label = 'Heavy Armor Plate', weight = 100, type = 'item', image = 't_armor_plate_heavy.png', unique = false, useable = true, shouldClose = true, description = '' },
    t_armor_plate_light           = { name = 't_armor_plate_light', label = 'Light Armor Plate', weight = 100, type = 'item', image = 't_armor_plate_light.png', unique = false, useable = true, shouldClose = true, description = '' },
    car_key                       = { name = 'car_key', label = 'Car Key', weight = 100, type = 'item', image = 'car_key.png', unique = true, useable = true, shouldClose = true, description = '' },

    -- tgiann bank
    creditcard_lvl_1              = { name = 'creditcard_lvl_1', label = 'Lost Credit Cards Normal', weight = 100, type = 'item', image = 'creditcard_lvl_1.png', unique = false, useable = true, shouldClose = true, description = '' },
    creditcard_lvl_2              = { name = 'creditcard_lvl_2', label = 'Lost Credit Cards Gold', weight = 100, type = 'item', image = 'creditcard_lvl_2.png', unique = false, useable = true, shouldClose = true, description = '' },
    creditcard_lvl_3              = { name = 'creditcard_lvl_3', label = 'Lost Credit Cards Platinum', weight = 100, type = 'item', image = 'creditcard_lvl_3.png', unique = false, useable = true, shouldClose = true, description = '' },

    -- tgiann-animpos-photo-cam
    polaroid                      = { name = 'polaroid', label = 'Polaroid Image', weight = 100, type = 'item', image = 'polaroid_image.png', unique = true, useable = true, shouldClose = true, description = '' },
    polaroid_empty                = { name = 'polaroid_empty', label = 'Empty Polaroid', weight = 100, type = 'item', image = 'polaroid_image.png', unique = false, useable = false, shouldClose = false, description = '' },

    -- tgiann-food-jobs
    packetlumipier                = { name = "packetlumipier", label = "Lumi Cafe", image = 'packetlumipier.png', weight = 100, type = "item", unique = true, useable = true, shouldClose = true, description = "" },
    packetbahama                  = { name = "packetbahama", label = "Bahama Mamas", image = 'packetbahama.png', weight = 100, type = "item", unique = true, useable = true, shouldClose = true, description = "" },
    packetbeanmachine             = { name = "packetbeanmachine", label = "Bean Machine Cafe", image = 'packetbeanmachine.png', weight = 100, type = "item", unique = true, useable = true, shouldClose = true, description = "" },
    packetburger                  = { name = "packetburger", label = "Burger Shot", image = 'packetburger.png', weight = 100, type = "item", unique = true, useable = true, shouldClose = true, description = "" },
    packethornys                  = { name = "packethornys", label = "Hornys", image = 'packethornys.png', weight = 100, type = "item", unique = true, useable = true, shouldClose = true, description = "" },
    packetkoi                     = { name = "packetkoi", label = "KOI", image = 'packetkoi.png', weight = 100, type = "item", unique = true, useable = true, shouldClose = true, description = "" },
    packetpearls                  = { name = "packetpearls", label = "Pearls", image = 'packetpearls.png', weight = 100, type = "item", unique = true, useable = true, shouldClose = true, description = "" },
    packetpizza                   = { name = "packetpizza", label = "Pizza This", image = 'packetpizza.png', weight = 100, type = "item", unique = true, useable = true, shouldClose = true, description = "" },
    packetdinner                  = { name = "packetdinner", label = "Pops Dinner", image = 'packetdinner.png', weight = 100, type = "item", unique = true, useable = true, shouldClose = true, description = "" },
    packettriads                  = { name = "packettriads", label = "Triads", image = 'packettriads.png', weight = 100, type = "item", unique = true, useable = true, shouldClose = true, description = "" },
    packetatom                    = { name = "packetatom", label = "Up un Atom", image = 'packetatom.png', weight = 100, type = "item", unique = true, useable = true, shouldClose = true, description = "" },
    packetuwu                     = { name = "packetuwu", label = "Cat Cafe", image = 'packetuwu.png', weight = 100, type = "item", unique = true, useable = true, shouldClose = true, description = "" },
    packetvanillaunicorn          = { name = "packetvanillaunicorn", label = "Vanilla Unicorn", image = 'packetvanillaunicorn.png', weight = 100, type = "item", unique = true, useable = true, shouldClose = true, description = "" },
    packettequilala               = { name = "packettequilala", label = "Tequi-la-la", image = 'packettequilala.png', weight = 100, type = "item", unique = true, useable = true, shouldClose = true, description = "" },
    packeticecream                = { name = "packeticecream", label = "Dondurmacı", image = 'packeticecream.png', weight = 100, type = "item", unique = true, useable = true, shouldClose = true, description = "" },
    -- Cocktail
    blue_lagoon                   = { name = "blue_lagoon", label = "Blue Lagoon", weight = 100, type = "item", image = "blue_lagoon.png", unique = true, useable = true, shouldClose = false, description = "" },
    midori_sour                   = { name = "midori_sour", label = "Midori Sour", weight = 100, type = "item", image = "midori_sour.png", unique = true, useable = true, shouldClose = false, description = "" },
    moscow_mule                   = { name = "moscow_mule", label = "Moscow Mule", weight = 100, type = "item", image = "moscow_mule.png", unique = true, useable = true, shouldClose = false, description = "" },
    pina_colada                   = { name = "pina_colada", label = "Pina Colada", weight = 100, type = "item", image = "pina_colada.png", unique = true, useable = true, shouldClose = false, description = "" },
    tom_collins                   = { name = "tom_collins", label = "Tom Collins", weight = 100, type = "item", image = "tom_collins.png", unique = true, useable = true, shouldClose = false, description = "" },
    espresso_martini              = { name = "espresso_martini", label = "Espresso Martini", weight = 100, type = "item", image = "espresso_martini.png", unique = true, useable = true, shouldClose = false, description = "" },
    grey_hound                    = { name = "grey_hound", label = "Grey Hound", weight = 100, type = "item", image = "grey_hound.png", unique = true, useable = true, shouldClose = false, description = "" },
    sex_on_the_beach              = { name = "sex_on_the_beach", label = "Sex On The Beach", weight = 100, type = "item", image = "sex_on_the_beach.png", unique = true, useable = true, shouldClose = false, description = "" },
    mojito                        = { name = "mojito", label = "Mojito", weight = 100, type = "item", image = "mojito.png", unique = true, useable = true, shouldClose = false, description = "" },
    tequila_sunrise               = { name = "tequila_sunrise", label = "Tequila Sunrise", weight = 100, type = "item", image = "tequila_sunrise.png", unique = true, useable = true, shouldClose = false, description = "" },
    old_fashioned                 = { name = "old_fashioned", label = "Old Fashioned", weight = 100, type = "item", image = "old_fashioned.png", unique = true, useable = true, shouldClose = false, description = "" },
    harvey_wallbanger             = { name = "harvey_wallbanger", label = "Harvey Wallbanger", weight = 100, type = "item", image = "harvey_wallbanger.png", unique = true, useable = true, shouldClose = false, description = "" },
    bellini                       = { name = "bellini", label = "Bellini", weight = 100, type = "item", image = "bellini.png", unique = true, useable = true, shouldClose = false, description = "" },
    bloody_mary                   = { name = "bloody_mary", label = "Bloody Mary", weight = 100, type = "item", image = "bloody_mary.png", unique = true, useable = true, shouldClose = false, description = "" },
    caiprinha                     = { name = "caiprinha", label = "Caiprinha", weight = 100, type = "item", image = "caiprinha.png", unique = true, useable = true, shouldClose = false, description = "" },
    cosmopolitan                  = { name = "cosmopolitan", label = "Cosmopolitan", weight = 100, type = "item", image = "cosmopolitan.png", unique = true, useable = true, shouldClose = false, description = "" },
    cuba_libre                    = { name = "cuba_libre", label = "Cuba Libre", weight = 100, type = "item", image = "cuba_libre.png", unique = true, useable = true, shouldClose = false, description = "" },
    gin_gimlit                    = { name = "gin_gimlit", label = "Gin Gimlit", weight = 100, type = "item", image = "gin_gimlit.png", unique = true, useable = true, shouldClose = false, description = "" },
    gin_tonic                     = { name = "gin_tonic", label = "Gin & Tonic", weight = 100, type = "item", image = "gin_tonic.png", unique = true, useable = true, shouldClose = false, description = "" },
    irish_coffee                  = { name = "irish_coffee", label = "Irish Coffee", weight = 100, type = "item", image = "irish_coffee.png", unique = true, useable = true, shouldClose = false, description = "" },
    mai_tai                       = { name = "mai_tai", label = "Mai Tai", weight = 100, type = "item", image = "mai_tai.png", unique = true, useable = true, shouldClose = false, description = "" },
    manhattan_martini             = { name = "manhattan_martini", label = "Manhattan Martini", weight = 100, type = "item", image = "manhattan_martini.png", unique = true, useable = true, shouldClose = false, description = "" },
    mimosa                        = { name = "mimosa", label = "Mimosa", weight = 100, type = "item", image = "mimosa.png", unique = true, useable = true, shouldClose = false, description = "" },
    mint_julep                    = { name = "mint_julep", label = "Mint JuleP", weight = 100, type = "item", image = "mint_julep.png", unique = true, useable = true, shouldClose = false, description = "" },
    raki                          = { name = "raki", label = "Raki", weight = 100, type = "item", image = "raki.png", unique = true, useable = true, shouldClose = false, description = "" },
    --Bear
    ale                           = { name = "ale", label = "Ale", weight = 100, type = "item", image = "ale.png", unique = true, useable = true, shouldClose = false, description = "" },
    blonde                        = { name = "blonde", label = "Blonde", weight = 100, type = "item", image = "blonde.png", unique = true, useable = true, shouldClose = false, description = "" },
    larger                        = { name = "larger", label = "Larger", weight = 100, type = "item", image = "larger.png", unique = true, useable = true, shouldClose = false, description = "" },
    pilsner                       = { name = "pilsner", label = "Pilsner", weight = 100, type = "item", image = "pilsner.png", unique = true, useable = true, shouldClose = false, description = "" },
    ryes                          = { name = "ryes", label = "Ryes", weight = 100, type = "item", image = "ryes.png", unique = true, useable = true, shouldClose = false, description = "" },
    --Wine
    bordeaux                      = { name = "bordeaux", label = "Bordeaux", weight = 100, type = "item", image = "bordeaux.png", unique = true, useable = true, shouldClose = false, description = "" },
    burgundy                      = { name = "burgundy", label = "Burgundy", weight = 100, type = "item", image = "burgundy.png", unique = true, useable = true, shouldClose = false, description = "" },
    cabernet                      = { name = "cabernet", label = "Cabernet", weight = 100, type = "item", image = "cabernet.png", unique = true, useable = true, shouldClose = false, description = "" },
    champ                         = { name = "champ", label = "Champ", weight = 100, type = "item", image = "champ.png", unique = true, useable = true, shouldClose = false, description = "" },
    chardonnay                    = { name = "chardonnay", label = "Chardonnay", weight = 100, type = "item", image = "chardonnay.png", unique = true, useable = true, shouldClose = false, description = "" },
    pinot_nior                    = { name = "pinot_nior", label = "Pinot Nior", weight = 100, type = "item", image = "pinot_nior.png", unique = true, useable = true, shouldClose = false, description = "" },
    white                         = { name = "white", label = "White", weight = 100, type = "item", image = "white.png", unique = true, useable = true, shouldClose = false, description = "" },
    zifandel                      = { name = "zifandel", label = "Zifandel", weight = 100, type = "item", image = "zifandel.png", unique = true, useable = true, shouldClose = false, description = "" },
    stout                         = { name = "stout", label = "stout", weight = 100, type = "item", image = "stout.png", unique = true, useable = true, shouldClose = false, description = "" },
    -- coffee
    nekolatte                     = { name = "nekolatte", label = "Neko Latte", weight = 100, type = "item", image = "nekolatte.png", unique = true, useable = true, shouldClose = true, description = "" },
    mocha                         = { name = "mocha", label = "Mocha", weight = 100, type = "item", image = "mocha.png", unique = true, useable = true, shouldClose = true, description = "" },
    cappuccino                    = { name = "cappuccino", label = "cappuccino", weight = 100, type = "item", image = "cappuccino.png", unique = true, useable = true, shouldClose = true, description = "" },
    latte                         = { name = "latte", label = "Latte", weight = 100, type = "item", image = "latte.png", unique = true, useable = true, shouldClose = true, description = "" },
    latte_macchiato               = { name = "latte_macchiato", label = "Latte Macchiato", weight = 100, type = "item", image = "latte_macchiato.png", unique = true, useable = true, shouldClose = true, description = "" },
    coffee                        = { name = "coffee", label = "coffee", weight = 0, type = "item", image = "coffee.png", unique = true, useable = true, shouldClose = true, description = "", },
    coffee_1x                     = { name = "coffee_1x", label = "small coffee", weight = 100, type = "item", image = "coffee_1x.png", unique = true, useable = true, shouldClose = true, description = "" },
    coffee_2x                     = { name = "coffee_2x", label = "medium coffee", weight = 100, type = "item", image = "coffee_2x.png", unique = true, useable = true, shouldClose = true, description = "" },
    coffee_3x                     = { name = "coffee_3x", label = "large coffee", weight = 100, type = "item", image = "coffee_3x.png", unique = true, useable = true, shouldClose = true, description = "" },
    -- Cola
    sprunk                        = { name = "sprunk", label = "Sprite", weight = 100, type = "item", image = "sprunk.png", unique = true, useable = true, shouldClose = true, description = "" },
    ecola                         = { name = "ecola", label = "Cola", weight = 100, type = "item", image = "ecola.png", unique = true, useable = true, shouldClose = true, description = "" },
    sprunklight                   = { name = "sprunklight", label = "Sprite Light", weight = 100, type = "item", image = "sprunklight.png", unique = true, useable = true, shouldClose = true, description = "" },
    ecolalight                    = { name = "ecolalight", label = "Cola Light", weight = 100, type = "item", image = "ecolalight.png", unique = true, useable = true, shouldClose = true, description = "" },
    -- Juices
    orange_juice                  = { name = "orange_juice", label = "Orange Juice", weight = 100, type = "item", image = "orange_juice.png", unique = true, useable = true, shouldClose = false, description = "" },
    watermelon_juice              = { name = "watermelon_juice", label = "Watermelon Juice", weight = 100, type = "item", image = "watermelon_juice.png", unique = true, useable = true, shouldClose = false, description = "" },
    pineapple_juice               = { name = "pineapple_juice", label = "Pineapple Juice", weight = 100, type = "item", image = "pineapple_juice.png", unique = true, useable = true, shouldClose = false, description = "" },
    carrot_juice                  = { name = "carrot_juice", label = "Carrot Juice", weight = 100, type = "item", image = "carrot_juice.png", unique = true, useable = true, shouldClose = false, description = "" },
    tomato_juice                  = { name = "tomato_juice", label = "Tomato Juice", weight = 100, type = "item", image = "tomato_juice.png", unique = true, useable = true, shouldClose = false, description = "" },
    cranberry_juice               = { name = "cranberry_juice", label = "Cranberry Juice", weight = 100, type = "item", image = "cranberry_juice.png", unique = true, useable = true, shouldClose = false, description = "" },
    lemonade_juice                = { name = "lemonade_juice", label = "Lemonade Juice", weight = 100, type = "item", image = "lemonade_juice.png", unique = true, useable = true, shouldClose = false, description = "" },
    --bubbletea
    bubbletea_strawberry          = { name = "bubbletea_strawberry", label = "Strawberry Bubble Tea", weight = 100, type = "item", image = "bubbletea_strawberry.png", unique = true, useable = true, shouldClose = true, description = "" },
    bubbletea_cola                = { name = "bubbletea_cola", label = "Cola Bubble Tea", weight = 100, type = "item", image = "bubbletea_cola.png", unique = true, useable = true, shouldClose = true, description = "" },
    bubbletea_green               = { name = "bubbletea_green", label = "Green Bubble Tea", weight = 100, type = "item", image = "bubbletea_green.png", unique = true, useable = true, shouldClose = true, description = "" },
    bubbletea_milk                = { name = "bubbletea_milk", label = "Milky Bubble Tea", weight = 100, type = "item", image = "bubbletea_milk.png", unique = true, useable = true, shouldClose = true, description = "" },
    bubbletea_caramel             = { name = "bubbletea_caramel", label = "Caramel Bubble Tea", weight = 100, type = "item", image = "bubbletea_caramel.png", unique = true, useable = true, shouldClose = true, description = "" },
    -- icecream
    berry_icecream                = { name = "berry_icecream", label = "Berry Ice cream", weight = 100, type = "item", image = "berry_icecream.png", unique = true, useable = true, shouldClose = true, description = "" },
    bubblegum_icecream            = { name = "bubblegum_icecream", label = "Bubblegum Ice cream", weight = 100, type = "item", image = "bubblegum_icecream.png", unique = true, useable = true, shouldClose = true, description = "" },
    caramel_icecream              = { name = "caramel_icecream", label = "Caramel Ice cream", weight = 100, type = "item", image = "caramel_icecream.png", unique = true, useable = true, shouldClose = true, description = "" },
    chocolate_icecream            = { name = "chocolate_icecream", label = "Chocolate Ice cream", weight = 100, type = "item", image = "chocolate_icecream.png", unique = true, useable = true, shouldClose = true, description = "" },
    chocolate_strawberry_icecream = { name = "chocolate_strawberry_icecream", label = "Strawberry&Chocolate Ice cream", weight = 100, type = "item", image = "chocolate_strawberry_icecream.png", unique = true, useable = true, shouldClose = true, description = "" },
    mint_icecream                 = { name = "mint_icecream", label = "Mint Ice cream", weight = 100, type = "item", image = "mint_icecream.png", unique = true, useable = true, shouldClose = true, description = "" },
    strawberry_icecream           = { name = "strawberry_icecream", label = "Strawberry Ice cream", weight = 100, type = "item", image = "strawberry_icecream.png", unique = true, useable = true, shouldClose = true, description = "" },
    strawberry_mint_icecream      = { name = "strawberry_mint_icecream", label = "Strawberry&Mint Ice cream", weight = 100, type = "item", image = "strawberry_mint_icecream.png", unique = true, useable = true, shouldClose = true, description = "" },
    strawberry_vanilla_icecream   = { name = "strawberry_vanilla_icecream", label = "Strawberry&Vanilla Ice cream", weight = 100, type = "item", image = "strawberry_vanilla_icecream.png", unique = true, useable = true, shouldClose = true, description = "" },
    vanilla_icecream              = { name = "vanilla_icecream", label = "Vanilla Ice cream", weight = 100, type = "item", image = "vanilla_icecream.png", unique = true, useable = true, shouldClose = true, description = "" },
    vanilla_berry_icecream        = { name = "vanilla_berry_icecream", label = "Berry&Vanilla Ice cream", weight = 100, type = "item", image = "vanilla_berry_icecream.png", unique = true, useable = true, shouldClose = true, description = "" },
    vanilla_mint_icecream         = { name = "vanilla_mint_icecream", label = "Mint&Vanilla Ice cream", weight = 100, type = "item", image = "vanilla_mint_icecream.png", unique = true, useable = true, shouldClose = true, description = "" },
    --food craft items
    carrot                        = { name = "carrot", label = "Carrot", weight = 100, type = "item", image = "carrot.png", unique = false, useable = true, shouldClose = true, description = "" },
    cranberry                     = { name = "cranberry", label = "Cranberry", weight = 100, type = "item", image = "cranberry.png", unique = false, useable = true, shouldClose = true, description = "" },
    boba                          = { name = "boba", label = "Boba", weight = 100, type = "item", image = "boba.png", unique = false, useable = true, shouldClose = true, description = "" },
    sugar                         = { name = "sugar", label = "Sugar", weight = 100, type = "item", image = "sugar.png", unique = false, useable = true, shouldClose = true, description = "" },
    blueberry                     = { name = "blueberry", label = "Blueberry", weight = 100, type = "item", image = "blueberry.png", unique = false, useable = true, shouldClose = true, description = "" },
    mint                          = { name = "mint", label = "Mint", weight = 100, type = "item", image = "mint.png", unique = false, useable = true, shouldClose = false, description = "" },
    orange                        = { name = "orange", label = "Orange", weight = 100, type = "item", image = "orange.png", unique = false, useable = true, shouldClose = false, description = "" },
    strawberry                    = { name = "strawberry", label = "Strawberry", weight = 100, type = "item", image = "strawberry.png", unique = false, useable = true, shouldClose = false, description = "" },
    rice                          = { name = "rice", label = "Rice", weight = 100, type = "item", image = "rice.png", unique = false, useable = true, shouldClose = true, description = "" },
    nori                          = { name = "nori", label = "Nori", weight = 100, type = "item", image = "nori.png", unique = false, useable = true, shouldClose = true, description = "" },
    tofu                          = { name = "tofu", label = "Tofu", weight = 100, type = "item", image = "tofu.png", unique = false, useable = true, shouldClose = true, description = "" },
    onion                         = { name = "onion", label = "Onion", weight = 500, type = "item", image = "onion.png", unique = false, useable = false, shouldClose = false, description = "" },
    avokado                       = { name = "avokado", label = "Avokado", weight = 500, type = "item", image = "avokado.png", unique = false, useable = false, shouldClose = false, description = "" },
    raw_sausagepizza              = { name = "raw_sausagepizza", label = "Raw Sausage Pizza", weight = 100, type = "item", image = "raw_sucuklu.png", unique = false, useable = true, shouldClose = false, description = "" },
    raw_margaritapizza            = { name = "raw_margaritapizza", label = "Raw Margaritalı Pizza", weight = 100, type = "item", image = "raw_margaritapizza.png", unique = false, useable = true, shouldClose = false, description = "" },
    raw_mushroompizza             = { name = "raw_mushroompizza", label = "Raw Mushroom Pizza", weight = 100, type = "item", image = "raw_mushroompizza.png", unique = false, useable = true, shouldClose = false, description = "" },
    raw_chickenpizza              = { name = "raw_chickenpizza", label = "Raw Chicken Pizza", weight = 100, type = "item", image = "raw_chickenpizza.png", unique = false, useable = true, shouldClose = false, description = "" },
    raw_tunapizza                 = { name = "raw_tunapizza", label = "Raw Tuna Pizza", weight = 100, type = "item", image = "raw_tunapizza.png", unique = false, useable = true, shouldClose = false, description = "" },
    milk                          = { name = "milk", label = "Milk", weight = 300, type = "item", image = "milk.png", unique = false, useable = true, shouldClose = true, description = "" },
    rawcoffee                     = { name = "rawcoffee", label = "Raw Coffee", weight = 100, type = "item", image = "rawcoffee.png", unique = false, useable = true, shouldClose = true, description = "", },
    sausage                       = { name = 'sausage', label = 'Sausage', weight = 100, type = 'item', image = 'sausage.png', unique = false, useable = true, shouldClose = true, description = '' },
    sausage_brat                  = { name = 'sausage_brat', label = 'Sausage', weight = 100, type = 'item', image = 'sausage_brat.png', unique = false, useable = true, shouldClose = true, description = '' },
    tuna                          = { name = 'tuna', label = 'Tuna', weight = 100, type = 'item', image = 'tuna.png', unique = false, useable = true, shouldClose = false, description = '' },
    chicken                       = { name = 'chicken', label = 'Chicken', weight = 100, type = 'item', image = 'chicken.png', unique = false, useable = true, shouldClose = false, description = '' },
    dough2                        = { name = 'dough2', label = 'Dough', weight = 100, type = 'item', image = 'dough2.png', unique = false, useable = true, shouldClose = false, description = '' },
    food_mushroom                 = { name = 'food_mushroom', label = 'Mushroom', weight = 100, type = 'item', image = 'food_mushroom.png', unique = false, useable = true, shouldClose = true, description = '' },
    spice                         = { name = "spice", label = "Spice", weight = 100, type = "item", image = "spice.png", unique = false, useable = true, shouldClose = false, description = "" },
    tomatoes                      = { name = 'tomatoes', label = 'Tomato', weight = 100, type = 'item', image = 'tomatoes.png', unique = false, useable = true, shouldClose = false, description = '' },
    tomatoes2                     = { name = 'tomatoes2', label = 'Cut Tomato', weight = 100, type = 'item', image = 'tomatoes2.png', unique = false, useable = true, shouldClose = false, description = '' },
    dough                         = { name = 'dough', label = 'Dough', weight = 100, type = 'item', image = 'dough.png', unique = false, useable = true, shouldClose = false, description = '' },
    tomatopaste                   = { name = 'tomatopaste', label = 'Tomatopaste', weight = 100, type = 'item', image = 'tomatopaste.png', unique = false, useable = true, shouldClose = false, description = '' },
    flour                         = { name = "flour", label = "Flour", weight = 100, type = "item", image = "flour.png", unique = false, useable = true, shouldClose = true, description = "" },
    egg                           = { name = 'egg', label = 'Eggs', weight = 100, type = 'item', image = 'egg.png', unique = false, useable = true, shouldClose = false, description = '' },
    kiwi                          = { name = "kiwi", label = "Kiwi", weight = 100, type = "item", image = "kiwi.png", unique = false, useable = true, shouldClose = false, description = "" },
    berry                         = { name = "berry", label = "Berry", weight = 100, type = "item", image = "berry.png", unique = false, useable = true, shouldClose = false, description = "" },
    lemon                         = { name = "lemon", label = "Lemon", weight = 100, type = "item", image = "lemon.png", unique = false, useable = true, shouldClose = false, description = "" },
    watermelon                    = { name = "watermelon", label = "Watermelon", weight = 100, type = "item", image = "watermelon.png", unique = false, useable = true, shouldClose = false, description = "" },
    banana                        = { name = "banana", label = "Banana", weight = 100, type = "item", image = "banana.png", unique = false, useable = true, shouldClose = false, description = "" },
    cherry                        = { name = "cherry", label = "Cherry", weight = 100, type = "item", image = "cherry.png", unique = false, useable = true, shouldClose = true, description = "" },
    maracuja                      = { name = "maracuja", label = "Maracuja", weight = 100, type = "item", image = "maracuja.png", unique = false, useable = true, shouldClose = true, description = "" },
    apple                         = { name = "apple", label = "Apple", weight = 100, type = "item", image = "apple.png", unique = false, useable = true, shouldClose = true, description = "" },
    burgerbread                   = { name = "burgerbread", label = "Burger Bread", weight = 100, type = "item", image = "burgerbread.png", unique = false, useable = true, shouldClose = true, description = "" },
    sandwichbread                 = { name = "sandwichbread", label = "Sandwich Bread", weight = 100, type = "item", image = "sandwichbread.png", unique = false, useable = true, shouldClose = true, description = "" },
    meat                          = { name = "meat", label = "Raw Meat", weight = 100, type = "item", image = "meat.png", unique = false, useable = true, shouldClose = true, description = "" },
    meat2                         = { name = "meat2", label = "Cooked Meat", weight = 100, type = "item", image = "meat2.png", unique = false, useable = true, shouldClose = true, description = "" },
    pickle                        = { name = "pickle", label = "Pickle", weight = 100, type = "item", image = "pickle.png", unique = false, useable = true, shouldClose = true, description = "" },
    pickle2                       = { name = "pickle2", label = "Cut Pickle", weight = 100, type = "item", image = "pickle2.png", unique = false, useable = true, shouldClose = true, description = "" },
    ketchup                       = { name = "ketchup", label = "Ketchup", weight = 100, type = "item", image = "ketchup.png", unique = false, useable = true, shouldClose = true, description = "" },
    mustard                       = { name = "mustard", label = "Mustard", weight = 100, type = "item", image = "mustard.png", unique = false, useable = true, shouldClose = true, description = "" },
    nugget                        = { name = "nugget", label = "Raw Nugget", weight = 100, type = "item", image = "nugget.png", unique = false, useable = true, shouldClose = true, description = "" },
    nugget2                       = { name = "nugget2", label = "Cooked Nugget", weight = 100, type = "item", image = "nugget2.png", unique = false, useable = true, shouldClose = true, description = "" },
    lettuce                       = { name = "lettuce", label = "Lettuce", weight = 100, type = "item", image = "lettuce.png", unique = false, useable = true, shouldClose = true, description = "" },
    lettuce2                      = { name = "lettuce2", label = "Cut Lettuce", weight = 100, type = "item", image = "lettuce2.png", unique = false, useable = true, shouldClose = true, description = "" },
    mayonnaise                    = { name = "mayonnaise", label = "Mayonnaise", weight = 100, type = "item", image = "mayonnaise.png", unique = false, useable = true, shouldClose = true, description = "" },
    potato                        = { name = "potato", label = "Potato", weight = 100, type = "item", image = "potato.png", unique = false, useable = true, shouldClose = true, description = "" },
    potato2                       = { name = "potato2", label = "Cut Potato", weight = 100, type = "item", image = "potato2.png", unique = false, useable = true, shouldClose = true, description = "" },
    grapefruit                    = { name = "grapefruit", label = "Greyfurt", weight = 100, type = "item", image = "grapefruit.png", unique = false, useable = true, shouldClose = true, description = "" },
    peach                         = { name = "peach", label = "Peach", weight = 100, type = "item", image = "peach.png", unique = false, useable = true, shouldClose = true, description = "" },
    pear                          = { name = "pear", label = "Pear", weight = 100, type = "item", image = "pear.png", unique = false, useable = true, shouldClose = true, description = "" },
    plum                          = { name = "plum", label = "Plum", weight = 100, type = "item", image = "plum.png", unique = false, useable = true, shouldClose = true, description = "" },
    cheese                        = { name = "cheese", label = "Pizza Cheese", weight = 100, type = "item", image = "cheese.png", unique = false, useable = true, shouldClose = true, description = "" },
    cheese2                       = { name = "cheese2", label = "Cut Pizza Cheese", weight = 100, type = "item", image = "cheese2.png", unique = false, useable = true, shouldClose = true, description = "" },
    ice                           = { name = "ice", label = "Ice", weight = 100, type = "item", image = "ice.png", unique = false, useable = true, shouldClose = true, description = "" },
    lime                          = { name = "lime", label = "Lime", weight = 100, type = "item", image = "lime.png", unique = false, useable = true, shouldClose = true, description = "" },
    alcohol                       = { name = "alcohol", label = "Alcohol", weight = 100, type = "item", image = "alcohol.png", unique = false, useable = true, shouldClose = true, description = "" },
    soda                          = { name = "soda", label = "Soda", weight = 100, type = "item", image = "soda.png", unique = false, useable = true, shouldClose = true, description = "" },
    pineapple                     = { name = "pineapple", label = "Pineapple", weight = 100, type = "item", image = "pineapple.png", unique = false, useable = true, shouldClose = true, description = "" },
    coconut                       = { name = "coconut", label = "Coconut", weight = 100, type = "item", image = "coconut.png", unique = false, useable = true, shouldClose = false, description = "" },
    espresso                      = { name = "espresso", label = "Espresso", weight = 100, type = "item", image = "espresso.png", unique = false, useable = true, shouldClose = false, description = "" },
    grape                         = { name = 'grape', label = 'Grape', weight = 100, type = 'item', image = 'grape.png', unique = false, useable = true, shouldClose = false, description = "" },
    vanilla                       = { name = 'vanilla', label = 'Vanilya', weight = 100, type = 'item', image = 'vanilla.png', unique = false, useable = true, shouldClose = false, description = "" },
    pepper                        = { name = 'pepper', label = 'Pepper', weight = 100, type = 'item', image = 'pepper.png', unique = false, useable = true, shouldClose = false, description = "" },
    noodles                       = { name = "noodles", label = "Noodle", weight = 100, type = "item", image = "noodles.png", unique = false, useable = false, shouldClose = true, description = "" },
    chocolate                     = { name = "chocolate", label = "Chocolate", weight = 100, type = "item", image = "chocolate.png", unique = false, useable = false, shouldClose = true, description = "" },
    caramel                       = { name = "caramel", label = "Caramel", weight = 100, type = "item", image = "caramel.png", unique = false, useable = false, shouldClose = true, description = "" },
    tortilla                      = { name = "tortilla", label = "Tortilla", weight = 100, type = "item", image = "tortilla.png", unique = false, useable = false, shouldClose = true, description = "" },
    cheddarcheese                 = { name = "cheddarcheese", label = "Cheddar Cheese", weight = 100, type = "item", image = "cheddarcheese.png", unique = false, useable = false, shouldClose = true, description = "" },
    tacosauce                     = { name = "tacosauce", label = "Taco Sauce", weight = 100, type = "item", image = "tacosauce.png", unique = false, useable = false, shouldClose = true, description = "" },
    --Food
    sandwich                      = { name = 'sandwich', label = 'Sandwich', weight = 200, type = 'item', image = 'sandwich.png', unique = true, useable = true, shouldClose = true, description = 'Nice bread for your stomach' },
    bento                         = { name = "bento", label = "Bento Box", weight = 500, type = "item", image = "bento.png", unique = true, useable = true, shouldClose = true, description = "" },
    miso                          = { name = "miso", label = "Miso Soup", weight = 100, type = "item", image = "miso.png", unique = true, useable = true, shouldClose = true, description = "" },
    spagetti                      = { name = "spagetti", label = "Spagetti", weight = 100, type = "item", image = "spagetti.png", unique = true, useable = true, shouldClose = true, description = "" },
    salad                         = { name = "salad", label = "Salad", weight = 100, type = "item", image = "salad.png", unique = true, useable = true, shouldClose = true, description = "" },
    hotdog                        = { name = "hotdog", label = "Hotdog", weight = 100, type = "item", image = "hotdog.png", unique = true, useable = true, shouldClose = true, description = "" },
    --sushi
    avosushi                      = { name = "avosushi", label = "Avokado Sushi", weight = 100, type = "item", image = "avosushi.png", unique = true, useable = true, shouldClose = true, description = "" },
    tonsushi                      = { name = "tonsushi", label = "Tuna Sushi", weight = 100, type = "item", image = "tonsushi.png", unique = true, useable = true, shouldClose = true, description = "" },
    --mochi
    pmochi                        = { name = "pmochi", label = "Pink Mochi", weight = 100, type = "item", image = "pmochi.png", unique = true, useable = true, shouldClose = true, description = "" },
    omochi                        = { name = "omochi", label = "Orange Mochi", weight = 100, type = "item", image = "omochi.png", unique = true, useable = true, shouldClose = true, description = "" },
    gmochi                        = { name = "gmochi", label = "Green Mochi", weight = 100, type = "item", image = "gmochi.png", unique = true, useable = true, shouldClose = true, description = "" },
    bmochi                        = { name = "bmochi", label = "Blue Mochi", weight = 100, type = "item", image = "bmochi.png", unique = true, useable = true, shouldClose = true, description = "" },
    --fires
    frenchfries                   = { name = "frenchfries", label = "French fries", weight = 100, type = "item", image = "frenchfries.png", unique = true, useable = true, shouldClose = true, description = "" },
    serratedfrenchfries           = { name = "serratedfrenchfries", label = "Serrated French fries", weight = 100, type = "item", image = "serratedfrenchfries.png", unique = true, useable = true, shouldClose = true, description = "" },
    --donut
    chocolate_donut               = { name = "chocolate_donut", label = "Chocolate Donut", weight = 100, type = "item", image = "chocolate_donut.png", unique = true, useable = true, shouldClose = true, description = "" },
    strawberry_donut              = { name = "strawberry_donut", label = "Strawberry Donut", weight = 100, type = "item", image = "strawberry_donut.png", unique = true, useable = true, shouldClose = true, description = "" },
    lemon_donut                   = { name = "lemon_donut", label = "Lemon Donut", weight = 100, type = "item", image = "lemon_donut.png", unique = true, useable = true, shouldClose = true, description = "" },
    mint_donut                    = { name = "mint_donut", label = "Mint Donut", weight = 100, type = "item", image = "mint_donut.png", unique = true, useable = true, shouldClose = true, description = "" },
    cherry_donut                  = { name = "cherry_donut", label = "Cherry Donut", weight = 100, type = "item", image = "cherry_donut.png", unique = true, useable = true, shouldClose = true, description = "" },
    creme_donut                   = { name = "creme_donut", label = "Cream Donut", weight = 100, type = "item", image = "creme_donut.png", unique = true, useable = true, shouldClose = true, description = "" },
    blueberry_donut               = { name = "blueberry_donut", label = "Blueberry Donut", weight = 100, type = "item", image = "blueberry_donut.png", unique = true, useable = true, shouldClose = true, description = "" },
    --Pizza
    uwupizza                      = { name = "uwupizza", label = "Uwu Pizza", weight = 100, type = "item", image = "uwupizza.png", unique = true, useable = true, shouldClose = true, description = "" },
    sausagepizza                  = { name = "sausagepizza", label = "Sausage Pizza", weight = 100, type = "item", image = "sausagepizza.png", unique = true, useable = true, shouldClose = false, description = "" },
    tunapizza                     = { name = "tunapizza", label = "Tuna Pizza", weight = 100, type = "item", image = "tunapizza.png", unique = true, useable = true, shouldClose = false, description = "" },
    chickenpizza                  = { name = "chickenpizza", label = "Chicken Pizza", weight = 100, type = "item", image = "chickenpizza.png", unique = true, useable = true, shouldClose = false, description = "" },
    mushroompizza                 = { name = "mushroompizza", label = "Mushroom Pizza", weight = 100, type = "item", image = "mushroompizza.png", unique = true, useable = true, shouldClose = false, description = "" },
    margaritapizza                = { name = "margaritapizza", label = "Margarita Pizza", weight = 100, type = "item", image = "margaritapizza.png", unique = true, useable = true, shouldClose = false, description = "" },
    --brownies
    whitechocolate_brownies       = { name = "whitechocolate_brownies", label = "White Chocolate Brownie", weight = 100, type = "item", image = "whitechocolate_brownies.png", unique = true, useable = true, shouldClose = false, description = "" },
    strawberry_brownies           = { name = "strawberry_brownies", label = "Strawberry Brownie", weight = 100, type = "item", image = "strawberry_brownies.png", unique = true, useable = true, shouldClose = false, description = "" },
    raspberry_brownies            = { name = "raspberry_brownies", label = "Raspberry Brownie", weight = 100, type = "item", image = "raspberry_brownies.png", unique = true, useable = true, shouldClose = false, description = "" },
    classic_brownies              = { name = "classic_brownies", label = "Brownie", weight = 100, type = "item", image = "classic_brownies.png", unique = true, useable = true, shouldClose = false, description = "" },
    --Cheesecake
    tiramisu                      = { name = "tiramisu", label = "Tiramisu", weight = 100, type = "item", image = "tiramisu.png", unique = true, useable = true, shouldClose = false, description = "" },
    chocolate_cheesecake          = { name = "chocolate_cheesecake", label = "White Chocolate Cheesecake", weight = 100, type = "item", image = "chocolate_cheesecake.png", unique = true, useable = true, shouldClose = false, description = "" },
    lemon_cheesecake              = { name = "lemon_cheesecake", label = "Lemon Cheesecake", weight = 100, type = "item", image = "lemon_cheesecake.png", unique = true, useable = true, shouldClose = false, description = "" },
    berry_cheesecake              = { name = "berry_cheesecake", label = "Berry Cheesecake", weight = 100, type = "item", image = "berry_cheesecake.png", unique = true, useable = true, shouldClose = false, description = "" },
    strawberry_cheesecake         = { name = "strawberry_cheesecake", label = "Strawberry Cheesecake", weight = 100, type = "item", image = "strawberry_cheesecake.png", unique = true, useable = true, shouldClose = false, description = "" },
    --Smoothie
    strawberry_smoothie           = { name = "strawberry_smoothie", label = "Strawberry Smoothie", weight = 100, type = "item", image = "strawberry_smoothie.png", unique = true, useable = true, shouldClose = false, description = "" },
    kiwi_smoothie                 = { name = "kiwi_smoothie", label = "Kiwi Smoothie", weight = 100, type = "item", image = "kiwi_smoothie.png", unique = true, useable = true, shouldClose = false, description = "" },
    berry_smoothie                = { name = "berry_smoothie", label = "Raspberry Smoothie", weight = 100, type = "item", image = "berry_smoothie.png", unique = true, useable = true, shouldClose = false, description = "" },
    orange_smoothie               = { name = "orange_smoothie", label = "Orange Smoothie", weight = 100, type = "item", image = "orange_smoothie.png", unique = true, useable = true, shouldClose = false, description = "" },
    banana_smoothie               = { name = "banana_smoothie", label = "Banana Smoothie", weight = 100, type = "item", image = "banana_smoothie.png", unique = true, useable = true, shouldClose = false, description = "" },
    --bagel
    bacon_egg_cheese_bagel        = { name = "bacon_egg_cheese_bagel", label = "Patırma, Yumurta ve Peynirli Simit", weight = 100, type = "item", image = "bacon_egg_cheese_bagel.png", unique = true, useable = true, shouldClose = false, description = "" },
    salmon_cream_bagel            = { name = "salmon_cream_bagel", label = "Salamlı Simit", weight = 100, type = "item", image = "salmon_cream_bagel.png", unique = true, useable = true, shouldClose = false, description = "" },
    --cake
    strawberry_cake               = { name = "strawberry_cake", label = "Strawberry Cake", weight = 100, type = "item", image = "strawberry_cake.png", unique = true, useable = true, shouldClose = true, description = "" },
    vanilla_cake                  = { name = "vanilla_cake", label = "Vanilla Cake", weight = 100, type = "item", image = "vanilla_cake.png", unique = true, useable = true, shouldClose = false, description = "" },
    chocolate_cake                = { name = "chocolate_cake", label = "Chocolate Cake", weight = 100, type = "item", image = "chocolate_cake.png", unique = true, useable = true, shouldClose = false, description = "" },
    --burger
    cheeseburger                  = { name = "cheeseburger", label = "Cheese Burger", weight = 100, type = "item", image = "cheeseburger.png", unique = true, useable = true, shouldClose = false, description = "" },
    chickenburger                 = { name = "chickenburger", label = "Chicken Burger", weight = 100, type = "item", image = "chickenburger.png", unique = true, useable = true, shouldClose = false, description = "" },
    burger_2x                     = { name = "burger_2x", label = "Double Hamburger", weight = 100, type = "item", image = "burger_2x.png", unique = true, useable = true, shouldClose = false, description = "" },
    burger_3x                     = { name = "burger_3x", label = "Tripple Hamburger", weight = 100, type = "item", image = "burger_3x.png", unique = true, useable = true, shouldClose = false, description = "" },
    burger_4x                     = { name = "burger_4x", label = "Stack Hamburger", weight = 100, type = "item", image = "burger_4x.png", unique = true, useable = true, shouldClose = false, description = "" },
    --kebab
    beef_kebab                    = { name = "beef_kebab", label = "Beef Kebap", weight = 100, type = "item", image = "beef_kebab.png", unique = true, useable = true, shouldClose = false, description = "" },
    chicken_kebab                 = { name = "chicken_kebab", label = "Chicken Kebap", weight = 100, type = "item", image = "chicken_kebab.png", unique = true, useable = true, shouldClose = false, description = "" },
    --taco
    beeftaco                      = { name = "beeftaco", label = "Beef Taco", weight = 100, type = "item", image = "beeftaco.png", unique = true, useable = true, shouldClose = false, description = "" },
    chickentaco                   = { name = "chickentaco", label = "Chicken Taco", weight = 100, type = "item", image = "chickentaco.png", unique = true, useable = true, shouldClose = false, description = "" },
    quesadilla                    = { name = "quesadilla", label = "Quesadilla", weight = 100, type = "item", image = "quesadilla.png", unique = true, useable = true, shouldClose = false, description = "" },
    --ramen
    ramen                         = { name = "ramen", label = "Ramen", weight = 100, type = "item", image = "ramen.png", unique = true, useable = true, shouldClose = false, description = "" },
    beef_ramen                    = { name = "beef_ramen", label = "Beef Ramen", weight = 100, type = "item", image = "beef_ramen.png", unique = true, useable = true, shouldClose = false, description = "" },
    chicken_ramen                 = { name = "chicken_ramen", label = "Chicken Ramen", weight = 100, type = "item", image = "chicken_ramen.png", unique = true, useable = true, shouldClose = false, description = "" },
    duck_ramen                    = { name = "duck_ramen", label = "Duck Ramen", weight = 100, type = "item", image = "duck_ramen.png", unique = true, useable = true, shouldClose = false, description = "" },
    shrimp_ramen                  = { name = "shrimp_ramen", label = "Shrimp Ramen", weight = 100, type = "item", image = "shrimp_ramen.png", unique = true, useable = true, shouldClose = false, description = "" },
    vegetable_ramen               = { name = "vegetable_ramen", label = "Vegetable Ramen", weight = 100, type = "item", image = "vegetable_ramen.png", unique = true, useable = true, shouldClose = false, description = "" },
    --Soup
    pumpkin_soup                  = { name = "pumpkin_soup", label = "Pumpkin Soup", weight = 100, type = "item", image = "pumpkin_soup.png", unique = true, useable = true, shouldClose = false, description = "" },
    vegetable_soup                = { name = "vegetable_soup", label = "Vegetable Soup", weight = 100, type = "item", image = "vegetable_soup.png", unique = true, useable = true, shouldClose = false, description = "" },
    chicken_noodle_soup           = { name = "chicken_noodle_soup", label = "Chicken noodle Soup", weight = 100, type = "item", image = "chicken_noodle_soup.png", unique = true, useable = true, shouldClose = false, description = "" },
    creamy_chicken_soup           = { name = "creamy_chicken_soup", label = "Creamy Chicken Soup", weight = 100, type = "item", image = "creamy_chicken_soup.png", unique = true, useable = true, shouldClose = false, description = "" },
    tomato_soup                   = { name = "tomato_soup", label = "Tomato Soupsı", weight = 100, type = "item", image = "tomato_soup.png", unique = true, useable = true, shouldClose = false, description = "" },
    mushroom_soup                 = { name = "mushroom_soup", label = "Mushroom Soup", weight = 100, type = "item", image = "mushroom_soup.png", unique = true, useable = true, shouldClose = false, description = "" },
    --macaroon
    banana_macaroon               = { name = "banana_macaroon", label = "Banana Macaroon", weight = 100, type = "item", image = "banana_macaroon.png", unique = true, useable = true, shouldClose = false, description = "" },
    orange_macaroon               = { name = "orange_macaroon", label = "Orange Macaroon", weight = 100, type = "item", image = "orange_macaroon.png", unique = true, useable = true, shouldClose = false, description = "" },
    strawberry_macaroon           = { name = "strawberry_macaroon", label = "Strawberry Macaroon", weight = 100, type = "item", image = "strawberry_macaroon.png", unique = true, useable = true, shouldClose = false, description = "" },
    mint_macaroon                 = { name = "mint_macaroon", label = "Mint Macaroon", weight = 100, type = "item", image = "mint_macaroon.png", unique = true, useable = true, shouldClose = false, description = "" },
    blueberry_macaroon            = { name = "blueberry_macaroon", label = "Blueberry Macaroon", weight = 100, type = "item", image = "blueberry_macaroon.png", unique = true, useable = true, shouldClose = false, description = "" },
    --muffin
    banana_muffin                 = { name = "banana_muffin", label = "Banana muffin", weight = 100, type = "item", image = "banana_muffin.png", unique = true, useable = true, shouldClose = false, description = "" },
    orange_muffin                 = { name = "orange_muffin", label = "Orange muffin", weight = 100, type = "item", image = "orange_muffin.png", unique = true, useable = true, shouldClose = false, description = "" },
    strawberry_muffin             = { name = "strawberry_muffin", label = "Strawberry muffin", weight = 100, type = "item", image = "strawberry_muffin.png", unique = true, useable = true, shouldClose = false, description = "" },
    mint_muffin                   = { name = "mint_muffin", label = "Mint muffin", weight = 100, type = "item", image = "mint_muffin.png", unique = true, useable = true, shouldClose = false, description = "" },
    berry_muffin                  = { name = "berry_muffin", label = "Berry muffin", weight = 100, type = "item", image = "berry_muffin.png", unique = true, useable = true, shouldClose = false, description = "" },
    --
    gps                           = { name = "gps", label = "GPS", weight = 100, type = "item", image = "gps.png", unique = true, useable = true, shouldClose = false, description = "" },
    pd_gps                        = { name = "pd_gps", label = "PD GPS", weight = 100, type = "item", image = "pd_gps.png", unique = true, useable = true, shouldClose = false, description = "" },

}
